### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by eculver** [JJWesterkamp/rx-postmessenger#1]
If someone were to use this code for any commercial purposes, things can get a little tricky. Could you add a license file that can allow users to attribute back to this project if that's the case?

**Comment by JJWesterkamp** [comment]
Hi, thanks for pointing that out! I meant to publish it under MIT license. I'll add it asap.

**Comment by JJWesterkamp** [comment]
Issue was resolved with commit 85ac6decdaeeec58d6580feb37358279d1c09735. The fix is shipped with npm releases as of version [1.0.0](https://github.com/JJWesterkamp/rx-postmessenger/releases/tag/v1.0.0).
