### ISSUE TITLE
Does not work with RxJS v7

### ISSUE THREAD

**Issue by rassie** [JJWesterkamp/rx-postmessenger#17]
The error message is 
`
Property '_deprecatedSyncErrorSubscribe' is missing in type 'import("/usr/src/app/node_modules/rx-postmessenger/node_modules/rxjs/internal/Observable").Observable<any>' but required in type 'import("/usr/src/app/node_modules/rxjs/dist/types/internal/Observable").Observable<any>'
`

I suspect that `rxjs` should be a peer dependency instead of dependency, so that app's RxJS is used instead of the one bundled with `rx-postmessenger`.

**Comment by JJWesterkamp** [comment]
Hi,

Thanks for your message.

I will start on a fix for this issue. I am not sure whether RxJS could be a peerDependency, though. RxJS is imported by rx-postmessenger, so this is strictly speaking not a standalone package. Besides that I require the RxJS module to be resolved for multiple reasons:

1. The Typescript type checker will error if the module is not found
2. I can not build UMD bundles without the RxJS package
3. For CI, the RxJS package must be automatically installed

I will do some research and try to circumvent these concerns.

**Comment by JounQin** [comment]
You can mark `rxjs` as `peer` and `dev` dependency at the same time.

**Comment by JJWesterkamp** [comment]
@rassie , @JounQin Using npm v7 I am able to make RxJS a peer dependency and still have it automatically installed. This issue is going to be solved with the linked PR.
