### ISSUE TITLE
Minor: unfinished comment

### ISSUE THREAD

**Issue by czim** [JJWesterkamp/rx-postmessenger#2]
https://github.com/JJWesterkamp/rx-postmessenger/blob/fb6be59096d3de94a31f39f61b28795920e3ea4b/src/rx-postmessenger.ts#L259

**Comment by JJWesterkamp** [comment]
Oops! I will ship a fix with the next patch release, which I plan to release shortly, where I'll also update the README and other documentation. Good catch!
